title: Around IT In 256 Seconds By Tomasz Nurkiewicz
tagline: Around IT In 256 Seconds By Tomasz Nurkiewicz
description: Podcast for developers, testers, SREsâ€¦ and their managers. I explain complex and convoluted technologies in a clear way, avoiding buzzwords and hype. Never longer than 4 minutes and 16 seconds.
logo: img/cover.jpg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://256.nurkiewicz.com"
twitter_username: tnurkiewicz
github_username:  nurkiewicz
permalink: /:year/:month/:title:output_ext
defaults:
  - scope:
      path: ""
    values:
      author: Tomasz Nurkiewicz
twitter:
  username: tnurkiewicz
  card: summary
remote_theme: brianmaierjr/long-haul
repository: nurkiewicz/256

social:
  github: nurkiewicz
  linkedin: nurkiewicz
  twitter: tnurkiewicz

feed:
  path: feeds/posts/default

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
